version: '3.7'
services:
  front:
    build: 
      context: ./dboard
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8999:80
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 9433:9433
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./db_data:/var/lib/postgresql/data  
      - ./initdb.sql:/docker-entrypoint-initdb.d/create_tables.sql
networks: 
  default: 
    external: 
      name: tulip-net 
volumes:
  db:
    driver: local      
